// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: services/key_maker/api/KeyMaker.proto

package KeyMaker

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type CreateUserKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEncryptionKey string `protobuf:"bytes,2,opt,name=userEncryptionKey,proto3" json:"userEncryptionKey,omitempty"`
}

func (x *CreateUserKeyRequest) Reset() {
	*x = CreateUserKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_key_maker_api_KeyMaker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserKeyRequest) ProtoMessage() {}

func (x *CreateUserKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_key_maker_api_KeyMaker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateUserKeyRequest) Descriptor() ([]byte, []int) {
	return file_services_key_maker_api_KeyMaker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserKeyRequest) GetUserEncryptionKey() string {
	if x != nil {
		return x.UserEncryptionKey
	}
	return ""
}

// The response message containing the greetings
type GetUserEncryptedKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserEncryptedKeyRequest) Reset() {
	*x = GetUserEncryptedKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_key_maker_api_KeyMaker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserEncryptedKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEncryptedKeyRequest) ProtoMessage() {}

func (x *GetUserEncryptedKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_key_maker_api_KeyMaker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEncryptedKeyRequest.ProtoReflect.Descriptor instead.
func (*GetUserEncryptedKeyRequest) Descriptor() ([]byte, []int) {
	return file_services_key_maker_api_KeyMaker_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserEncryptedKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ChangeUserKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	OldKey string `protobuf:"bytes,1,opt,name=oldKey,proto3" json:"oldKey,omitempty"`
	NewKey string `protobuf:"bytes,2,opt,name=newKey,proto3" json:"newKey,omitempty"`
}

func (x *ChangeUserKeyRequest) Reset() {
	*x = ChangeUserKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_key_maker_api_KeyMaker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserKeyRequest) ProtoMessage() {}

func (x *ChangeUserKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_key_maker_api_KeyMaker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserKeyRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserKeyRequest) Descriptor() ([]byte, []int) {
	return file_services_key_maker_api_KeyMaker_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeUserKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangeUserKeyRequest) GetOldKey() string {
	if x != nil {
		return x.OldKey
	}
	return ""
}

func (x *ChangeUserKeyRequest) GetNewKey() string {
	if x != nil {
		return x.NewKey
	}
	return ""
}

var File_services_key_maker_api_KeyMaker_proto protoreflect.FileDescriptor

var file_services_key_maker_api_KeyMaker_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6b, 0x65, 0x79, 0x5f, 0x6d,
	0x61, 0x6b, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x4b, 0x65, 0x79, 0x4d, 0x61, 0x6b, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x4b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x14, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6c,
	0x64, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x6c, 0x64, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x4b, 0x65, 0x79, 0x32, 0xe6, 0x01, 0x0a, 0x08, 0x4b,
	0x65, 0x79, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x15, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65,
	0x64, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4b,
	0x65, 0x79, 0x12, 0x15, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x4b, 0x65, 0x79, 0x4d, 0x61, 0x6b, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_key_maker_api_KeyMaker_proto_rawDescOnce sync.Once
	file_services_key_maker_api_KeyMaker_proto_rawDescData = file_services_key_maker_api_KeyMaker_proto_rawDesc
)

func file_services_key_maker_api_KeyMaker_proto_rawDescGZIP() []byte {
	file_services_key_maker_api_KeyMaker_proto_rawDescOnce.Do(func() {
		file_services_key_maker_api_KeyMaker_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_key_maker_api_KeyMaker_proto_rawDescData)
	})
	return file_services_key_maker_api_KeyMaker_proto_rawDescData
}

var file_services_key_maker_api_KeyMaker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_key_maker_api_KeyMaker_proto_goTypes = []any{
	(*CreateUserKeyRequest)(nil),       // 0: CreateUserKeyRequest
	(*GetUserEncryptedKeyRequest)(nil), // 1: GetUserEncryptedKeyRequest
	(*ChangeUserKeyRequest)(nil),       // 2: ChangeUserKeyRequest
	(*empty.Empty)(nil),                // 3: google.protobuf.Empty
	(*wrappers.StringValue)(nil),       // 4: google.protobuf.StringValue
}
var file_services_key_maker_api_KeyMaker_proto_depIdxs = []int32{
	0, // 0: KeyMaker.CreateUserFromKey:input_type -> CreateUserKeyRequest
	1, // 1: KeyMaker.GetUserEncryptedKey:input_type -> GetUserEncryptedKeyRequest
	2, // 2: KeyMaker.ChangeUserKey:input_type -> ChangeUserKeyRequest
	3, // 3: KeyMaker.CreateUserFromKey:output_type -> google.protobuf.Empty
	4, // 4: KeyMaker.GetUserEncryptedKey:output_type -> google.protobuf.StringValue
	3, // 5: KeyMaker.ChangeUserKey:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_key_maker_api_KeyMaker_proto_init() }
func file_services_key_maker_api_KeyMaker_proto_init() {
	if File_services_key_maker_api_KeyMaker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_key_maker_api_KeyMaker_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateUserKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_key_maker_api_KeyMaker_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserEncryptedKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_key_maker_api_KeyMaker_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ChangeUserKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_key_maker_api_KeyMaker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_key_maker_api_KeyMaker_proto_goTypes,
		DependencyIndexes: file_services_key_maker_api_KeyMaker_proto_depIdxs,
		MessageInfos:      file_services_key_maker_api_KeyMaker_proto_msgTypes,
	}.Build()
	File_services_key_maker_api_KeyMaker_proto = out.File
	file_services_key_maker_api_KeyMaker_proto_rawDesc = nil
	file_services_key_maker_api_KeyMaker_proto_goTypes = nil
	file_services_key_maker_api_KeyMaker_proto_depIdxs = nil
}
